const form=document.querySelector('#posForm'),itemsBox=document.querySelector('#billItems'),statusBox=document.querySelector('#posStatus'),invoice=document.querySelector('#invoice');
const money=value=>`₹${Number(value||0).toLocaleString('en-IN',{maximumFractionDigits:2})}`;
function addItem(item={}){const row=document.createElement('div');row.className='bill-item';row.innerHTML=`<input class="item-name" required placeholder="Product name" value="${item.name||''}"><input class="item-qty" required type="number" min="1" value="${item.quantity||1}" aria-label="Quantity"><input class="item-price" required type="number" min="0" placeholder="Price" value="${item.price||''}" aria-label="Price"><button class="remove-item" type="button" aria-label="Remove item">×</button>`;row.querySelectorAll('input').forEach(input=>input.addEventListener('input',updateTotal));row.querySelector('.remove-item').onclick=()=>{if(itemsBox.children.length>1)row.remove();updateTotal()};itemsBox.append(row)}
function readItems(){return [...itemsBox.children].map(row=>({name:row.querySelector('.item-name').value.trim(),quantity:Number(row.querySelector('.item-qty').value||1),price:Number(row.querySelector('.item-price').value||0)}))}
function updateTotal(){const subtotal=readItems().reduce((sum,item)=>sum+item.quantity*item.price,0),discount=Math.max(0,Number(document.querySelector('#discount').value||0));document.querySelector('#billTotal').textContent=money(Math.max(0,subtotal-discount))}
async function api(url,options={}){const response=await fetch(url,{credentials:'same-origin',headers:{'Content-Type':'application/json'},...options});const data=await response.json();if(!response.ok)throw new Error(data.error||'Unable to create bill');return data}
async function checkAccess(){try{await api('/api/admin/stats');document.querySelector('#posAccess').hidden=true;form.hidden=false}catch{document.querySelector('#posAccess').hidden=false;form.hidden=true}}
function invoiceMessage(sale){return `Thank you for shopping with ZLOON!\nInvoice: ${sale.id}\nAmount paid: ${money(sale.total)}\nPayment: ${sale.paymentMethod.toUpperCase()}\nItems: ${sale.items.map(item=>`${item.name} x${item.quantity}`).join(', ')}\nBring your fit. Own the vibe.`}
function showInvoice(order,customer){const message=invoiceMessage(order),phone=String(customer.phone).replace(/\D/g,'');document.querySelector('#invoiceId').textContent=order.id;document.querySelector('#invoiceBody').innerHTML=`<p><strong>${customer.name}</strong><br>${customer.city}${customer.email?` · ${customer.email}`:''}<br>${customer.phone}</p><table><thead><tr><th>Item</th><th>Qty</th><th>Amount</th></tr></thead><tbody>${order.items.map(item=>`<tr><td>${item.name}</td><td>${item.quantity}</td><td>${money(item.price*item.quantity)}</td></tr>`).join('')}</tbody></table><p class="invoice-total">Paid total: ${money(order.total)}</p><p>Payment: ${order.paymentMethod.toUpperCase()} · Offline store sale</p>`;document.querySelector('#sendWhatsapp').href=`https://wa.me/${phone}?text=${encodeURIComponent(message)}`;document.querySelector('#sendSms').href=`sms:+${phone}?body=${encodeURIComponent(message)}`;invoice.hidden=false;invoice.scrollIntoView({behavior:'smooth'})}
function makeLocalOrder(customer,items,discount){const subtotal=items.reduce((sum,item)=>sum+item.quantity*item.price,0);return {id:`ZL-POS-${Math.random().toString(16).slice(2,8).toUpperCase()}`,customerName:customer.name,customerEmail:customer.email||'',customerPhone:String(customer.phone).replace(/\D/g,''),items,address:{line1:'ZLOON offline store sale',city:customer.city,pincode:'—'},paymentMethod:customer.paymentMethod,status:'Paid offline sale',offline:true,discount,total:Math.max(0,subtotal-discount),createdAt:new Date().toISOString()}}
form.addEventListener('submit',async event=>{event.preventDefault();statusBox.textContent='Creating bill...';const customer=Object.fromEntries(new FormData(form)),items=readItems(),discount=Number(customer.discount||0);try{const sale=await api('/api/admin/offline-orders',{method:'POST',body:JSON.stringify({customer,items,discount,paymentMethod:customer.paymentMethod})});showInvoice(sale.order,customer);statusBox.textContent='Bill saved in Admin Orders successfully.'}catch(error){const order=makeLocalOrder(customer,items,discount),saved=JSON.parse(localStorage.getItem('zloonOfflineOrders')||'[]');saved.unshift(order);localStorage.setItem('zloonOfflineOrders',JSON.stringify(saved.slice(0,100)));showInvoice(order,customer);statusBox.textContent='Bill saved on this device. It will show in Admin Orders after refresh.'}});
document.querySelector('#addItem').onclick=()=>addItem();document.querySelector('#discount').addEventListener('input',updateTotal);document.querySelector('#printInvoice').onclick=()=>window.print();document.querySelector('#newBill').onclick=()=>{form.reset();itemsBox.innerHTML='';addItem();updateTotal();invoice.hidden=true;statusBox.textContent=''};addItem();checkAccess();
