/* ZLOON local server. Set ADMIN_PASSWORD and SESSION_SECRET before production. */
const http=require('http'),https=require('https'),fs=require('fs'),path=require('path'),crypto=require('crypto');
const ROOT=__dirname,DATA=path.join(ROOT,'data','zloon-data.json'),PORT=process.env.PORT||4173;
const sessions=new Map();
const hash=value=>crypto.scryptSync(value,'zloon-auth-salt',64).toString('hex');
const random=bytes=>crypto.randomBytes(bytes).toString('hex');
function ensureData(){fs.mkdirSync(path.dirname(DATA),{recursive:true});if(!fs.existsSync(DATA))fs.writeFileSync(DATA,JSON.stringify({customers:[],visits:[],settings:{whatsappNumber:process.env.ZLOON_WHATSAPP_NUMBER||''},admin:{email:process.env.ADMIN_EMAIL||'admin@zloon.in',passwordHash:hash(process.env.ADMIN_PASSWORD||random(24))}}))}
function read(){ensureData();const db=JSON.parse(fs.readFileSync(DATA,'utf8'));db.settings={whatsappNumber:'919782326637',...(db.settings||{})};if(!db.settings.whatsappNumber||db.settings.whatsappNumber==='919324968619')db.settings.whatsappNumber='919782326637';db.bookings=db.bookings||[];db.catalog=db.catalog||[];db.inventory=db.inventory||[];db.orders=db.orders||[];db.careerApplications=db.careerApplications||[];return db}function write(data){fs.writeFileSync(DATA,JSON.stringify(data,null,2))}
function json(res,status,body,cookie){res.writeHead(status,{'Content-Type':'application/json','Cache-Control':'no-store',...(cookie?{'Set-Cookie':cookie}:{}),'Access-Control-Allow-Origin':'same-origin'});res.end(JSON.stringify(body))}
function parseCookies(req){return Object.fromEntries((req.headers.cookie||'').split(';').filter(Boolean).map(x=>x.trim().split('=')))}
function session(req){const id=parseCookies(req).zloon_session;if(!id)return null;const active=sessions.get(id);if(active)return active;const db=read(),saved=(db.adminSessions||[]).find(item=>item.id===id&&item.expires>Date.now());if(saved?.admin){sessions.set(id,saved);return saved}return null}function setSession(res,user){const id=random(24),created=Date.now(),maxAge=user.admin?2592000:28800,record={...user,created,expires:created+maxAge*1000};sessions.set(id,record);if(user.admin){const db=read();db.adminSessions=(db.adminSessions||[]).filter(item=>item.expires>Date.now()).slice(-9);db.adminSessions.push({id,admin:true,created,expires:record.expires});write(db)}return `zloon_session=${id}; HttpOnly; SameSite=Lax; Path=/; Max-Age=${maxAge}`}
function body(req){return new Promise((resolve,reject)=>{let raw='';req.on('data',c=>raw+=c);req.on('end',()=>{try{resolve(raw?JSON.parse(raw):{})}catch{reject(new Error('Invalid request'))}})})}
function track(page){const db=read();db.visits.push({page,time:new Date().toISOString()});db.visits=db.visits.slice(-1000);write(db)}
function admin(req,res){const s=session(req);if(!s?.admin){json(res,401,{error:'Admin login required'});return false}return true}
function customer(req,res){const s=session(req);if(!s?.customerId){json(res,401,{error:'Customer login required'});return null}return s.customerId}
function validSlot(type,date,time){const d=new Date(`${date}T${time}:00`),mins=d.getHours()*60+d.getMinutes();if(Number.isNaN(d))return false;if(type==='spotlight')return d.getDay()===0&&mins>=1140&&mins<=1257&&mins%3===0;if(type==='dressing')return mins>=540&&mins<=1230&&mins%30===0;return false}
function sendWhatsappTemplate(to,name,parameters=[]){const token=process.env.WHATSAPP_ACCESS_TOKEN,phoneId=process.env.WHATSAPP_PHONE_NUMBER_ID,version=process.env.WHATSAPP_API_VERSION||'v22.0';if(!token||!phoneId||!name)return Promise.resolve(false);const payload=JSON.stringify({messaging_product:'whatsapp',to:String(to).replace(/\D/g,''),type:'template',template:{name,language:{code:'en_US'},components:parameters.length?[{type:'body',parameters:parameters.map(text=>({type:'text',text:String(text)}))}]:[]}});return new Promise((resolve,reject)=>{const r=https.request({hostname:'graph.facebook.com',path:`/${version}/${phoneId}/messages`,method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json','Content-Length':Buffer.byteLength(payload)}},res=>{let data='';res.on('data',c=>data+=c);res.on('end',()=>res.statusCode>=200&&res.statusCode<300?resolve(true):reject(new Error(`WhatsApp delivery failed: ${data}`)))});r.on('error',reject);r.write(payload);r.end()})}function sendWhatsappOtp(to,code){return sendWhatsappTemplate(to,process.env.WHATSAPP_OTP_TEMPLATE||'zloon_login_otp',[code])}
async function api(req,res,url){try{if(req.method==='POST'&&url.pathname==='/api/track'){const {page}=await body(req);track(String(page||'index.html'));return json(res,200,{ok:true})}
if(req.method==='GET'&&url.pathname==='/api/config'){const db=read();return json(res,200,{whatsappNumber:db.settings?.whatsappNumber||''})}
if(req.method==='GET'&&url.pathname==='/api/catalog'){const db=read();return json(res,200,{items:db.catalog})}
if(req.method==='POST'&&url.pathname==='/api/careers'){const {name,email,phone,city,type,role,education,experience,portfolio,message}=await body(req);if(!name||!email||!phone||!city||!type||!role||!message)return json(res,400,{error:'Please complete all required career details.'});const db=read(),application={id:`CA-${random(4).toUpperCase()}`,name:String(name).slice(0,70),email:String(email).slice(0,120),phone:String(phone).slice(0,30),city:String(city).slice(0,70),type:String(type).slice(0,40),role:String(role).slice(0,80),education:String(education||'').slice(0,120),experience:String(experience||'').slice(0,40),portfolio:String(portfolio||'').slice(0,240),message:String(message).slice(0,1000),createdAt:new Date().toISOString()};db.careerApplications.unshift(application);write(db);return json(res,201,{application})}
if(req.method==='POST'&&url.pathname==='/api/auth/request-verification'){const {name,email,phone,city,member}=await body(req);if(!name||!email||!phone||!city)return json(res,400,{error:'Please complete all customer details.'});const code=String(Math.floor(100000+Math.random()*900000)),token=random(18);sessions.set(`verify_${token}`,{name,email,phone,city,member:Boolean(member),code,expires:Date.now()+600000});let delivered=false;try{delivered=await sendWhatsappOtp(phone,code)}catch(e){if(process.env.NODE_ENV==='production')return json(res,502,{error:'WhatsApp OTP could not be delivered. Please retry.'})}return json(res,200,{token,expiresIn:600,whatsappDelivered:delivered,devCode:delivered||process.env.NODE_ENV==='production'?undefined:code})}
if(req.method==='POST'&&url.pathname==='/api/auth/verify'){const {token,code}=await body(req),pending=sessions.get(`verify_${token}`);if(!pending||pending.expires<Date.now()||pending.code!==String(code))return json(res,400,{error:'Invalid or expired verification code.'});sessions.delete(`verify_${token}`);const db=read(),now=new Date().toISOString();let customer=db.customers.find(c=>c.email===pending.email);if(customer)Object.assign(customer,pending,{lastLogin:now});else{customer={id:random(8),...pending,verified:true,joinedAt:now,lastLogin:now};db.customers.unshift(customer)}write(db);return json(res,200,{customer:{name:customer.name,email:customer.email,phone:customer.phone,city:customer.city,member:customer.member,verified:true},},setSession(res,{customerId:customer.id}))}
if(req.method==='GET'&&url.pathname==='/api/auth/me'){const s=session(req);if(!s?.customerId)return json(res,401,{error:'Not logged in'});const c=read().customers.find(x=>x.id===s.customerId);return c?json(res,200,{customer:{name:c.name,email:c.email,phone:c.phone,city:c.city,member:c.member,verified:true}}):json(res,401,{error:'Not logged in'})}
if(req.method==='POST'&&url.pathname==='/api/auth/logout'){const id=parseCookies(req).zloon_session;sessions.delete(id);if(id){const db=read();if(db.adminSessions){db.adminSessions=db.adminSessions.filter(item=>item.id!==id);write(db)}}return json(res,200,{ok:true},'zloon_session=; HttpOnly; Path=/; Max-Age=0')}
if(req.method==='POST'&&url.pathname==='/api/bookings'){const customerId=customer(req,res);if(!customerId)return;const {type,date,time}=await body(req),db=read(),c=db.customers.find(x=>x.id===customerId);if(!['spotlight','dressing'].includes(type)||!validSlot(type,date,time))return json(res,400,{error:'Please choose a valid available slot.'});if(type==='dressing'&&!c?.member)return json(res,403,{error:'Dressing slots are available for Zloon Plus members only.'});if(db.bookings.some(b=>b.type===type&&b.date===date&&b.time===time))return json(res,409,{error:'This slot has already been booked.'});const booking={id:random(6),customerId,type,date,time,status:'confirmed',createdAt:new Date().toISOString()};db.bookings.push(booking);write(db);let whatsappDelivered=false;if(type==='spotlight'){try{whatsappDelivered=await sendWhatsappTemplate(c?.phone,process.env.WHATSAPP_SPOTLIGHT_TEMPLATE||'',[c?.name||'ZLOON member',date,time])}catch{}}return json(res,201,{booking,whatsappDelivered})}
if(req.method==='POST'&&url.pathname==='/api/orders'){const sessionCustomerId=session(req)?.customerId;const {items,address,paymentMethod,customer:guest}=await body(req);if(!Array.isArray(items)||!items.length)return json(res,400,{error:'Your Style Bag is empty.'});if(!address?.line1||!address?.city||!address?.pincode)return json(res,400,{error:'Please enter your delivery address and PIN code.'});if(!sessionCustomerId&&(!guest?.name||!guest?.phone||!guest?.email))return json(res,400,{error:'Please complete your contact details.'});const db=read(),c=sessionCustomerId?db.customers.find(x=>x.id===sessionCustomerId):null,safeItems=items.slice(0,20).map(x=>({name:String(x.name||'ZLOON look').slice(0,80),size:String(x.size||'Not selected').slice(0,20),color:String(x.color||'Not selected').slice(0,30),quantity:Math.max(1,Math.min(10,Number(x.quantity)||1)),price:Math.max(0,Number(String(x.price||'').replace(/[^0-9.]/g,''))||0)})),total=safeItems.reduce((sum,item)=>sum+item.price*item.quantity,0),order={id:`ZL-${random(4).toUpperCase()}`,customerId:sessionCustomerId||null,customerName:c?.name||String(guest.name).slice(0,70),customerEmail:c?.email||String(guest.email).slice(0,120),customerPhone:c?.phone||String(guest.phone).slice(0,30),items:safeItems,address:{line1:String(address.line1).slice(0,180),city:String(address.city).slice(0,70),pincode:String(address.pincode).slice(0,12)},paymentMethod:paymentMethod==='cod'?'cod':'whatsapp',status:'New enquiry',total,createdAt:new Date().toISOString()};db.orders.unshift(order);write(db);return json(res,201,{order})}
if(req.method==='POST'&&url.pathname==='/api/admin/offline-orders'){if(!admin(req,res))return;const {customer,items,discount,paymentMethod}=await body(req),name=String(customer?.name||'').trim(),phone=String(customer?.phone||'').replace(/\D/g,''),city=String(customer?.city||'').trim(),safeItems=Array.isArray(items)?items.map(item=>({name:String(item.name||'').trim().slice(0,80),quantity:Math.max(1,Math.min(99,Number(item.quantity)||1)),price:Math.max(0,Number(item.price)||0)})).filter(item=>item.name):[];if(!name||phone.length<10||!city||!safeItems.length)return json(res,400,{error:'Customer name, mobile number, city and at least one item are required.'});const db=read(),subtotal=safeItems.reduce((sum,item)=>sum+item.quantity*item.price,0),safeDiscount=Math.min(subtotal,Math.max(0,Number(discount)||0)),order={id:`ZL-POS-${random(3).toUpperCase()}`,customerId:null,customerName:name,customerEmail:String(customer?.email||'').slice(0,120),customerPhone:phone,items:safeItems,address:{line1:'ZLOON offline store sale',city,pincode:'—'},paymentMethod:['cash','upi','card'].includes(paymentMethod)?paymentMethod:'cash',status:'Paid offline sale',offline:true,discount:safeDiscount,total:subtotal-safeDiscount,note:String(customer?.note||'').slice(0,500),createdAt:new Date().toISOString()};db.orders.unshift(order);write(db);return json(res,201,{order})}
if(req.method==='POST'&&url.pathname==='/api/admin/login'){const {email,password}=await body(req),a=read().admin;if(email!==a.email||hash(password||'')!==a.passwordHash)return json(res,401,{error:'Incorrect admin email or password.'});return json(res,200,{ok:true},setSession(res,{admin:true}))}
if(req.method==='GET'&&url.pathname==='/api/admin/stats'){if(!admin(req,res))return;const db=read(),members=db.customers.filter(c=>c.member);return json(res,200,{customers:db.customers,visits:db.visits,bookings:db.bookings,orders:db.orders,catalog:db.catalog,inventory:db.inventory,careerApplications:db.careerApplications,totalCustomers:db.customers.length,members:members.length,conversion:db.customers.length?Math.round(members.length/db.customers.length*100):0})}
if(req.method==='POST'&&url.pathname==='/api/admin/inventory'){if(!admin(req,res))return;const {name,sku,quantity,movement,note}=await body(req),qty=Number(quantity),db=read();if(!name||!Number.isInteger(qty)||qty<1||!['in','out'].includes(movement))return json(res,400,{error:'Enter item name, whole quantity, and stock movement.'});const item=db.inventory.find(x=>x.sku===String(sku||name).trim())||{id:random(6),name:String(name).trim(),sku:String(sku||name).trim(),quantity:0,history:[]};if(movement==='out'&&item.quantity<qty)return json(res,400,{error:'Not enough stock available for this stock-out entry.'});item.quantity+=movement==='in'?qty:-qty;item.history.unshift({movement,quantity:qty,note:String(note||''),time:new Date().toISOString()});if(!db.inventory.some(x=>x.id===item.id))db.inventory.unshift(item);write(db);return json(res,201,{item})}
if(req.method==='POST'&&url.pathname==='/api/admin/whatsapp'){if(!admin(req,res))return;const {number}=await body(req),clean=String(number||'').replace(/\D/g,'');if(clean&&clean.length<10)return json(res,400,{error:'Enter a valid WhatsApp number with country code.'});const db=read();db.settings={...(db.settings||{}),whatsappNumber:clean};write(db);return json(res,200,{whatsappNumber:clean})}
if(req.method==='POST'&&url.pathname==='/api/admin/upload'){if(!admin(req,res))return;const {name,collection,dataUrl}=await body(req),match=String(dataUrl||'').match(/^data:image\/(jpeg|jpg|png|webp);base64,([A-Za-z0-9+/=]+)$/);if(!match||!['men','women'].includes(collection))return json(res,400,{error:'Upload a valid JPG, PNG, or WEBP fashion image.'});const bytes=Buffer.from(match[2],'base64');if(bytes.length>5*1024*1024)return json(res,400,{error:'Image must be 5 MB or smaller.'});const ext=match[1]==='jpeg'?'jpg':match[1],id=random(10);fs.mkdirSync(path.join(ROOT,'uploads'),{recursive:true});fs.writeFileSync(path.join(ROOT,'uploads',`${id}.${ext}`),bytes);const db=read(),item={id,name:String(name||'ZLOON new look').slice(0,70),collection,url:`uploads/${id}.${ext}`,createdAt:new Date().toISOString()};db.catalog.unshift(item);write(db);return json(res,201,{item})}
return json(res,404,{error:'Not found'})}catch(e){return json(res,500,{error:e.message||'Server error'})}}
const types={'.html':'text/html; charset=utf-8','.js':'application/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.jpg':'image/jpeg','.JPG':'image/jpeg','.png':'image/png','.webp':'image/webp'};
const server=http.createServer((req,res)=>{const url=new URL(req.url,'http://localhost');if(url.pathname.startsWith('/api/'))return api(req,res,url);const safe=path.normalize(decodeURIComponent(url.pathname==='/'?'/index.html':url.pathname)).replace(/^([.][.][\\/])+/,''),file=path.join(ROOT,safe);if(!file.startsWith(ROOT)||!fs.existsSync(file)||fs.statSync(file).isDirectory()){res.writeHead(404);return res.end('Not found')}res.writeHead(200,{'Content-Type':types[path.extname(file)]||'application/octet-stream'});fs.createReadStream(file).pipe(res)});
if(require.main===module){ensureData();server.listen(PORT,'0.0.0.0',()=>console.log(`ZLOON server running at http://localhost:${PORT}`))}module.exports={server,read,write};
