(() => {
  const key = 'zloon_wishlist';
  const products = [
    ['Blue Paisley Kurti','women.html','₹799'],['Sage Bow Top','women.html','₹499'],['Red Mesh Top','women.html','₹499'],['Lilac Rib Top','women.html','₹499'],['Blue Floral Puff Top','women.html','₹499'],['Sunny Comfort Top','women.html','₹499'],['Tropical Print Top','women.html','₹499'],['Black Chic Top','women.html','₹499'],
    ['Indigo Relaxed Set','men.html','₹799'],['Cityline Overshirt','men.html','₹799'],['Weekend Polo','men.html','₹799'],['Slate Cargo Trouser','men.html','₹799'],['Midnight Bomber','men.html','₹999'],['Cloud White Tee','men.html','₹499']
  ];
  const esc = value => String(value || '').replace(/[&<>'"]/g, char => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[char]));
  const get = () => { try { return JSON.parse(localStorage.getItem(key) || '[]'); } catch { return []; } };
  const save = items => { localStorage.setItem(key, JSON.stringify(items)); updateCount(); };
  function updateCount(){ const count = get().length; document.querySelectorAll('[data-wishlist-count]').forEach(node => node.textContent = count); }
  function add(item){ const saved = get(); if(saved.some(entry => entry.name === item.name)) return; saved.unshift(item); save(saved); }
  function remove(name){ save(get().filter(item => item.name !== name)); renderWishlist(); }
  function renderResults(query=''){ const target=document.querySelector('#zloonSearchResults'); if(!target)return; const list=products.filter(product=>product[0].toLowerCase().includes(query.toLowerCase())).slice(0,8); target.innerHTML=list.length?list.map(([name,href,price])=>`<a href="${href}"><span>${esc(name)}</span><small>${price} · View collection</small></a>`).join(''):'<p>No matching ZLOON looks found.</p>'; }
  function renderWishlist(){ const target=document.querySelector('#zloonWishlistItems'); if(!target)return; const items=get(); target.innerHTML=items.length?items.map(item=>`<div><a href="${esc(item.href || 'women.html')}"><strong>${esc(item.name)}</strong><small>${esc(item.price || '')}</small></a><button type="button" data-remove-wishlist="${esc(item.name)}">Remove</button></div>`).join(''):'<p>Your wishlist is empty. Tap ♡ on any product to save it.</p>'; target.querySelectorAll('[data-remove-wishlist]').forEach(button=>button.onclick=()=>remove(button.dataset.removeWishlist)); }
  function inject(){ if(document.querySelector('#zloonQuickTools'))return; document.body.insertAdjacentHTML('beforeend',`<div class="zloon-quick-tools" id="zloonQuickTools"><button type="button" id="zloonSearchOpen">⌕ <span>Search</span></button><button type="button" id="zloonWishlistOpen">♡ <span>Wishlist</span><b data-wishlist-count>0</b></button></div><div class="zloon-tool-modal" id="zloonSearchModal" hidden><div class="zloon-tool-card"><button class="tool-close" type="button">×</button><p class="tool-kicker">ZLOON SEARCH</p><h2>Find your next fit</h2><input id="zloonSearchInput" placeholder="Search tops, denim, dresses, polos…" autocomplete="off"><div id="zloonSearchResults"></div></div></div><div class="zloon-tool-modal" id="zloonWishlistModal" hidden><div class="zloon-tool-card"><button class="tool-close" type="button">×</button><p class="tool-kicker">SAVED LOOKS</p><h2>Your ZLOON Wishlist</h2><div id="zloonWishlistItems"></div></div></div>`);
    const close=modal=>{modal.hidden=true}; const searchModal=document.querySelector('#zloonSearchModal'),wishModal=document.querySelector('#zloonWishlistModal'); const openSearch=()=>{searchModal.hidden=false;renderResults();setTimeout(()=>document.querySelector('#zloonSearchInput').focus(),0)};const openWishlist=()=>{wishModal.hidden=false;renderWishlist()}; document.querySelector('#zloonSearchOpen').onclick=openSearch; document.querySelector('#zloonWishlistOpen').onclick=openWishlist; [searchModal,wishModal].forEach(modal=>{modal.querySelector('.tool-close').onclick=()=>close(modal);modal.onclick=event=>{if(event.target===modal)close(modal)}});document.querySelector('#zloonSearchInput').oninput=event=>renderResults(event.target.value);document.querySelectorAll('.nav').forEach(nav=>{if(nav.querySelector('.zloon-header-tools'))return;nav.insertAdjacentHTML('beforeend',`<div class="zloon-header-tools"><button type="button" data-header-search aria-label="Search"><svg viewBox="0 0 24 24"><circle cx="10.8" cy="10.8" r="7.2"></circle><path d="m16.2 16.2 5 5"></path></svg></button><button type="button" data-header-profile aria-label="Profile"><svg viewBox="0 0 24 24"><circle cx="12" cy="7" r="4"></circle><path d="M4.5 21c.7-4 3.2-6 7.5-6s6.8 2 7.5 6"></path></svg></button><button type="button" class="header-bag" data-header-bag aria-label="Shopping bag"><svg viewBox="0 0 24 24"><path d="M5 8h14l-1 13H6L5 8Z"></path><path d="M9 9V6a3 3 0 0 1 6 0v3"></path></svg><b data-wishlist-count style="display:none"></b></button><button type="button" data-header-wishlist aria-label="Wishlist"><svg viewBox="0 0 24 24"><path d="M20.8 4.9a5.4 5.4 0 0 0-7.6 0L12 6.1l-1.2-1.2a5.4 5.4 0 0 0-7.6 7.6L12 21l8.8-8.5a5.4 5.4 0 0 0 0-7.6Z"></path></svg></button></div>`)});document.querySelectorAll('[data-header-search]').forEach(button=>button.onclick=openSearch);document.querySelectorAll('[data-header-wishlist]').forEach(button=>button.onclick=openWishlist);document.querySelectorAll('[data-header-profile]').forEach(button=>button.onclick=()=>{const login=document.querySelector('.login-btn');if(login)login.click();else location.href='index.html'});document.querySelectorAll('[data-header-bag]').forEach(button=>button.onclick=()=>{const bag=document.querySelector('#bagButton');if(bag)bag.click();else location.href='checkout.html'}); updateCount();
  }
  function decorateProducts(){ document.querySelectorAll('.catalog-card').forEach(card=>{ if(card.querySelector('.wishlist-product'))return; const name=card.querySelector('h3')?.textContent?.trim(); if(!name)return; const price=card.querySelector('.catalog-price')?.textContent?.trim() || ''; const button=document.createElement('button'); button.type='button';button.className='wishlist-product';button.textContent='♡';button.title='Save to wishlist';button.onclick=event=>{event.preventDefault();event.stopPropagation();add({name,price,href:location.pathname.includes('men')?'men.html':'women.html'});button.textContent='♥'};card.appendChild(button); }); const productName=document.querySelector('#productName')?.textContent?.trim(); const actions=document.querySelector('.product-page-actions'); if(productName&&actions&&!document.querySelector('#productWishlistButton')){const button=document.createElement('button');button.id='productWishlistButton';button.type='button';button.textContent='♡ Save to Wishlist';button.onclick=()=>{add({name:productName,price:document.querySelector('#productPrice')?.textContent||'',href:location.href});button.textContent='♥ Saved'};actions.appendChild(button)} }
  function startTools(){inject();decorateProducts();new MutationObserver(decorateProducts).observe(document.body,{childList:true,subtree:true});}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',startTools);else startTools();
})();
